# Generated by Django 4.2.20 on 2025-05-14 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('video_file', models.FileField(upload_to='videos/originals/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('youtube_video_id', models.CharField(blank=True, max_length=50, null=True)),
                ('youtube_upload_status', models.CharField(blank=True, max_length=30, null=True)),
                ('original_file_cleaned_up', models.BooleanField(default=False)),
                ('processed_file_cleaned_up', models.BooleanField(default=False)),
                ('processed_video_file', models.FileField(blank=True, null=True, upload_to='videos/processed/')),
                ('processing_status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('processing_log', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FrameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField(db_index=True)),
                ('player_label', models.IntegerField()),
                ('combat_state', models.CharField(blank=True, max_length=50, null=True)),
                ('shoulder_left_x', models.FloatField(blank=True, null=True)),
                ('shoulder_left_y', models.FloatField(blank=True, null=True)),
                ('shoulder_right_x', models.FloatField(blank=True, null=True)),
                ('shoulder_right_y', models.FloatField(blank=True, null=True)),
                ('elbow_left_x', models.FloatField(blank=True, null=True)),
                ('elbow_left_y', models.FloatField(blank=True, null=True)),
                ('elbow_right_x', models.FloatField(blank=True, null=True)),
                ('elbow_right_y', models.FloatField(blank=True, null=True)),
                ('wrist_left_x', models.FloatField(blank=True, null=True)),
                ('wrist_left_y', models.FloatField(blank=True, null=True)),
                ('wrist_right_x', models.FloatField(blank=True, null=True)),
                ('wrist_right_y', models.FloatField(blank=True, null=True)),
                ('hip_left_x', models.FloatField(blank=True, null=True)),
                ('hip_left_y', models.FloatField(blank=True, null=True)),
                ('hip_right_x', models.FloatField(blank=True, null=True)),
                ('hip_right_y', models.FloatField(blank=True, null=True)),
                ('knee_left_x', models.FloatField(blank=True, null=True)),
                ('knee_left_y', models.FloatField(blank=True, null=True)),
                ('knee_right_x', models.FloatField(blank=True, null=True)),
                ('knee_right_y', models.FloatField(blank=True, null=True)),
                ('ankle_left_x', models.FloatField(blank=True, null=True)),
                ('ankle_left_y', models.FloatField(blank=True, null=True)),
                ('ankle_right_x', models.FloatField(blank=True, null=True)),
                ('ankle_right_y', models.FloatField(blank=True, null=True)),
                ('left_leg_angle', models.FloatField(blank=True, null=True)),
                ('right_leg_angle', models.FloatField(blank=True, null=True)),
                ('front_leg', models.IntegerField(blank=True, null=True)),
                ('front_wrist', models.IntegerField(blank=True, null=True)),
                ('arm_base_distance', models.FloatField(blank=True, null=True)),
                ('cup_above', models.IntegerField(blank=True, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_data', to='api_mmpose.video')),
            ],
            options={
                'ordering': ['video', 'frame_number', 'player_label'],
                'unique_together': {('video', 'frame_number', 'player_label')},
            },
        ),
    ]
