# Generated by Django 4.2.20 on 2025-05-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mmpose', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_upload_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
